FROM maven:3.8.1-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

RUN openjdk:17.0.1-jdk-slim
COPY --from=build /target/management-0.0.1-SNAPSHOT.jar management.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar",""management.jar"]